version: "3.8"
services:
  jenkins:
    build:
      context: .
      dockerfile: dockerfiles/jenkins.Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks: [jenkins-net]

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports: ["9000:9000"]
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks: [jenkins-net]

  registry:
    image: registry:2
    container_name: registry
    ports: ["5000:5000"]
    networks: [jenkins-net]

volumes:
  jenkins_home:
networks:
  jenkins-net:
    driver: bridge
